[package]
name = "yserver"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lib]
name = "yserver"
path = "src/lib.rs"

[[bin]]
name = "ynest"
path = "src/bin/ynest.rs"

[[bin]]
name = "yserver"
path = "src/bin/yserver.rs"

[dependencies]
ash.workspace = true
crossbeam-channel.workspace = true
drm.workspace = true
env_logger.workspace = true
fontconfig = "0.11"
freetype-rs.workspace = true
gpu-allocator.workspace = true
input.workspace = true
libc.workspace = true
log.workspace = true
nix.workspace = true
signal-hook.workspace = true
thiserror.workspace = true
udev.workspace = true
xkbcommon.workspace = true
yserver-core.workspace = true
yserver-protocol.workspace = true

[lints]
workspace = true
